# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to GitHub pages

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Update the data
        run: |
          cd src
          node parseData.js
      - name: Deploy to GH Pages
        run: |
          git config --global user.email "mehdi.bounya@gmail.com"
          git config --global user.name "mehdibo"
          git remote set-url origin https://${{ secrets.githubToken }}@github.com/mehdibo/coronamap-ma.git
          npm run deploy
